project:
  type: website
  output-dir: docs

website:
  favicon: profile.jpg
  title: "Home"
  site-url: https://kr9268.github.io/ # 사이트맵에 필요
  site-path: "/" # 사이트맵에 필요
  google-analytics: "G-LPL499WQBH"
  navbar:
    left:
      - text: Blog
        href: index.qmd
      - text: Dashboards
        href: dashboards.qmd
    right:
      - text: About me
        href: about.qmd
      - icon: github
        href: https://github.com/KR9268
      - icon: linkedin
        href: https://www.linkedin.com/in/%EA%B8%B0%EB%B3%B5-%EB%B0%95-573a68268/
      - icon: rss
        href: index.xml
  comments: 
    giscus:
      repo: kr9268/kr9268.github.io
  margin-footer: Copyright © 2024 Kibok Park All rights reserved.

  

format:
  html:
    theme:
      light: [flatly]
      dark : [Darkly]
    css: styles.css
    copy: false


